apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg\?background\=%23fff
  memberOf: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: austinal
spec:
  profile:
    displayName: Austina Lin
    email: austinal@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/gweresch@example.com.svg\?background\=%23fff
  memberOf: [default-team]
